"""fixed model name

Revision ID: d23b58999d00
Revises: 84820de404d7
Create Date: 2025-08-17 17:16:20.275690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23b58999d00'
down_revision = '84820de404d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('decription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decription', sa.TEXT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
